@echo off
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1

set BUILD_DIR=c:\s\MS\ninja_build_rel

if exist "%BUILD_DIR%\CMakeCache.txt" goto build

echo Configuring fast (RelWithDebInfo) build...
"C:\Qt\Tools\CMake_64\bin\cmake.exe" -S c:\s\MS -B "%BUILD_DIR%" -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DQt6_DIR=C:/Qt/6.10.1/msvc2022_64/lib/cmake/Qt6 -DMUSESCORE_BUILD_CONFIGURATION=app -DMUSE_QT_SUPPORT=ON -DMUE_BUILD_COMPOSING_TESTS=ON -DMUE_BUILD_BRAILLE_TESTS=OFF -DMUE_BUILD_ENGRAVING_TESTS=OFF -DMUE_BUILD_CONVERTER_TESTS=OFF -DMUE_BUILD_IMPORTEXPORT_TESTS=OFF -DMUE_BUILD_NOTATIONSCENE_TESTS=OFF -DMUE_BUILD_NOTATION_TESTS=OFF -DMUE_BUILD_PLAYBACK_TESTS=OFF -DMUE_BUILD_PROJECT_TESTS=OFF -DMUE_BUILD_UNIT_TESTS=OFF -DMUE_BUILD_IMPEXP_BB_MODULE=OFF -DMUE_BUILD_IMPEXP_BWW_MODULE=OFF -DMUE_BUILD_IMPEXP_CAPELLA_MODULE=OFF -DMUE_BUILD_IMPEXP_MUSEDATA_MODULE=OFF -DMUE_BUILD_IMPEXP_OVE_MODULE=OFF -DMUE_BUILD_IMPEXP_TABLEDIT_MODULE=OFF -DMUE_BUILD_IMPEXP_AUDIOEXPORT_MODULE=OFF -DMUE_BUILD_IMPEXP_VIDEOEXPORT_MODULE=OFF -DMUE_BUILD_IMPEXP_LYRICS_MODULE=OFF
if errorlevel 1 (
    echo CMake configuration failed.
    exit /b 1
)
echo Configuration done.

:build
cd /d "%BUILD_DIR%"
ninja composing_tests MuseScore5.exe batch_analyze
