// GENERATED by idiom_discovery/run_vl_feature_space.py — DO NOT EDIT BY HAND.
// VL-C texture-classifier reference set (spec cowork_voiceleading_axis_design.md §5.3).
//
// PROVENANCE (the shipped-parameter contract, §5.3):
//   run          : run_vl_feature_space.py feature-space measurement, CC 2026-07-03
//   corpus state : study cache vl_records.pkl — 2102 pieces / 45 note-level sources
//                  (findings v2.0; cc_vl_idiom_discovery_report.md)
//   feature space: WINNER = z-scored concatenation (ABz); nearest-centroid reproduces
//                  the ratified AB K=4 partition at ARI=0.791 accuracy=0.918
//                  (two-stage 0.716, motion-only 0.258 — §5.3 candidates).
//   clustering   : KMeans(K=4, random_state=0, n_init=10), sklearn 1.9.0; cap=80/source
//   fit space    : mean/std over the cap=80 fit set (n=1409); z-space euclidean nearest-centroid.
//   feature order (20-d): A[0..11]=P(|iv|=k) k0..11, A[12]=P(|iv|>=12), A[13]=repeat,
//                  A[14]=step, A[15]=leap, B[16]=parallel, B[17]=similar, B[18]=contrary, B[19]=oblique.
#pragma once
#include <array>

namespace mu::composing::analysis::voiceleading {

inline constexpr int kVlFeatureDim = 20;
inline constexpr int kVlTextureClassCount = 4;

// Raw-feature normalization (subtract mean, divide by std+1e-9) then nearest-centroid in z-space.
inline constexpr std::array<double, 20> kVlRefMean = { 0.111097945, 0.175497795, 0.243679987, 0.0995233237, 0.0708212637, 0.0833471145, 0.0183093491, 0.0591050614, 0.0227146692, 0.0228276691, 0.0146353501, 0.00665431252, 0.0717861585, 0.111097945, 0.419177783, 0.469724272, 0.0436298614, 0.0884649606, 0.109889031, 0.758016147 };
inline constexpr std::array<double, 20> kVlRefStd  = { 0.0834753772, 0.0771656267, 0.116203517, 0.053066257, 0.0401415969, 0.0326702142, 0.0200659441, 0.0376663883, 0.0195011845, 0.0218940193, 0.016476618, 0.00873026147, 0.0639049487, 0.0834753772, 0.18101032, 0.207640713, 0.0509998461, 0.0605203532, 0.0803472909, 0.161537453 };

// Class centroids in z-space, in enum order (Contrapuntal, HomophonicClassical, HomophonicPianistic, ModerateMixed).
inline constexpr std::array<std::array<double, 20>, 4> kVlRefCentroidZ = {{
    {{ 0.0446282799, 0.94227396, 1.18892953, -1.00429858, -0.796241481, -0.256690888, -0.712035041, -0.418484565, -0.732881949, -0.782113035, -0.726358216, -0.629458393, -0.657570505, 0.0446282799, 1.16495543, -1.03348864, 0.773846679, 1.29209573, 1.38273262, -1.41616059 }},  // Contrapuntal (n=325)
    {{ -0.334772892, -0.182098935, -0.347908494, 0.554049832, 0.369391399, 0.0790550238, 0.201014444, 0.0691109203, 0.328075661, 0.297464163, 0.278094151, 0.231377105, 0.148093661, -0.334772892, -0.300977146, 0.39696099, -0.413270654, -0.54779997, -0.600863342, 0.634574388 }},  // HomophonicClassical (n=395)
    {{ -0.572316578, -1.22136924, -1.20802644, 0.762976975, 0.967463844, 0.724456143, 0.989624764, 0.821029761, 0.893927249, 0.929128974, 0.854664111, 0.867827213, 1.08271187, -0.572316578, -1.29619486, 1.36003669, -0.291462735, -0.426698976, -0.500149811, 0.500653001 }},  // HomophonicPianistic (n=329)
    {{ 0.850064599, 0.465334786, 0.412395718, -0.398533523, -0.570629795, -0.517078519, -0.482155179, -0.448361447, -0.515292549, -0.469430669, -0.430459061, -0.4787087, -0.558329963, 0.850064599, 0.463121019, -0.745466267, 0.0212027144, -0.175461561, -0.13193832, 0.124667976 }},  // ModerateMixed (n=360)
}};

// Precision-phase floor DEFAULTS derived from the fit distribution over the fit set (documented, NOT tuned).
inline constexpr double kVlFitScaleDefault  = 2.6734128;  // median best-distance
inline constexpr double kVlFitFloorDefault  = 0.129574792;  // ~p05 of best-fit exp(-dBest/scale)
inline constexpr double kVlMarginFloorDefault = 0.00718666965;  // ~p05 of best-vs-second fit margin

} // namespace mu::composing::analysis::voiceleading
