#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────────────────────
# OI-170 — regenerate cc_oi170_measurements.txt, the generated artifact every figure in
# cc_oi170_measure_report.md is cited from (#17f: no hand-transcribed measurement numbers).
#
# This assembles, in one pass: the Task-1 enumeration sweeps (1, 1b/1c the SCOPE CHECK, 2..5),
# the three corpus arms per preset (OFF / counters-on / variant-on), the whole-file byte-identity
# of the variant corpus, the line-level key diff of the differing files, the hard stop on the
# variant corpus, and the golden check.
#
# ★ THE SCOPE CHECK (SWEEP 1b/1c) IS LOAD-BEARING — DO NOT DROP IT. A scoped sweep proves
#   completeness of the SCOPE, never of the QUESTION (DEFECT_TYPES.md DT-26). It is what caught
#   OI-175 (a live, chord-deciding tonic site two directories outside the L4 scope). Two traps,
#   both hit on this script's first run and both now closed here:
#     * the scope exclusion must be ANCHORED on exact paths — a bare `notationcomposingbridge`
#       substring also swallows notationcomposingbridgehelpers.{cpp,h} and silently drops hits;
#     * the remainder listing must be DERIVED from that same exclusion (never a hand-kept file
#       list), and RECONCILED arithmetically — tree-wide − scoped must equal the per-file sum,
#       or the run prints a STOP. Only the arithmetic caught the substring bug.
#
# ★ REBUILD FIRST. Both probe flags are read once at static init and a corpus run does NOT
#   rebuild, so an arm measures whatever binary is on disk. This artifact's first generation was
#   produced by a binary one source-edit stale and was NOT established (#16/#19). Stamp the arm
#   to the BUILD, not to the working tree.
#
# Usage (from the repo root, after a build and after running the nine arms):
#     bash tools/cc_oi170_measure_artifact.sh <arms-root> <suite-log-dir> [<out>]
#
#   <arms-root>     dir holding off/<preset>, cnt/<preset>, var/<preset> and a8_var/, e.g.
#                   the scratch root the arms were written to (never tools/corpus — DT-24).
#   <suite-log-dir> dir holding t_composing.txt, t_notation.txt, t_snap.txt, a8.log, rsd.log.
#   <out>           output path (default: cc_oi170_measurements.txt).
#
# Reproduce the arms themselves (each writes to a scratch dir; the committed corpus is untouched):
#     python tools/run_bach_preset.py --preset <P> --output-dir <arms-root>/off/<p>
#     MU_KEY_COLLECTION_PROBE=1 python tools/run_bach_preset.py --preset <P> --output-dir <arms-root>/cnt/<p>
#     MU_KEY_COLLECTION_PROBE=1 MU_KEY_COLLECTION_SIGMASK_VARIANT=1 \
#         python tools/run_bach_preset.py --preset <P> --output-dir <arms-root>/var/<p>
#     python tools/a8_rebaseline_measure.py --out-dir <arms-root>/a8_var --corpus-root <arms-root>/var  > <logs>/a8.log
#     python tools/robust_stop_diff.py --candidate <arms-root>/a8_var                                   > <logs>/rsd.log
# ─────────────────────────────────────────────────────────────────────────────────────────────
set -u

R="${1:?usage: cc_oi170_measure_artifact.sh <arms-root> <suite-log-dir> [<out>]}"
SP="${2:?usage: cc_oi170_measure_artifact.sh <arms-root> <suite-log-dir> [<out>]}"
OUT="${3:-cc_oi170_measurements.txt}"

# The tonic-derived constructions. Comments are INCLUDED so a commented-out use cannot hide.
SW='keyTonicPc|keyModeTonicOffset|ionianTonicPcFromFifths|keyModeScaleIntervals|diatonicDegreeForRootPc'
# The dispatch's L4 scope: the region/gate/refinement path + the diatonicToKey producer/consumers.
L4DIRS="src/composing/analysis/chord src/composing/analysis/function src/composing/analysis/region src/composing/analysis/section src/notation/internal/notationcomposingbridge.cpp src/notation/internal/notationimplodebridge.cpp"
# The same scope as an ANCHORED exclusion, for the remainder listing (see the header note).
EXCL='analysis/(chord|function|region|section)/|internal/notationcomposingbridge\.cpp$|internal/notationimplodebridge\.cpp$'

sweep_all()  { grep -rnE "$SW" src/composing src/notation --include=*.cpp --include=*.h 2>/dev/null | grep -v "/tests/"; }
sweep_l4()   { grep -rnE "$SW" $L4DIRS --include=*.cpp --include=*.h 2>/dev/null | grep -v "/tests/"; }
remainder_files() {
    grep -rlE "$SW" src/composing src/notation --include=*.cpp --include=*.h 2>/dev/null \
        | grep -v "/tests/" | grep -vE "$EXCL"
}

{
echo "# OI-170 — RAW MEASURED OUTPUT (generated artifact; the report cites these figures, never re-types them)"
echo "# generated by tools/cc_oi170_measure_artifact.sh (this file is NOT hand-edited — regenerate it)"
echo "# which drives: tools/cc_oi168_probe_report.py + tools/a8_rebaseline_measure.py + tools/robust_stop_diff.py"
echo "# instrument commit: $(git rev-parse --short HEAD)  + this session's default-OFF instrumentation (uncommitted at generation time)"
echo "# corpus reference: tools/corpus/{baroque,jazz,default}   arms root: $R"
echo "#"
echo "# PROVENANCE: both probe flags are read once at static init and a corpus run does NOT rebuild, so"
echo "# an arm measures whatever binary is on disk. This artifact's FIRST generation came from a binary"
echo "# built BEFORE the last source edit to chordanalyzer.cpp — its stamp to the committed source was"
echo "# broken and no figure it carried was established (#16/#19). Every arm below was re-run on a binary"
echo "# built from the exact committed source. Stamp the arm to the BUILD, not to the working tree."
echo "# suites at the instrumented build (both flags OFF), verbatim from the test output:"
echo "#   composing_tests        : $(grep -E '^\[  PASSED  \]' "$SP/t_composing.txt" | tail -1)"
echo "#   notation_tests         : $(grep -E '^\[  PASSED  \]' "$SP/t_notation.txt" | tail -1)"
echo "#   pipeline_snapshot_tests: $(grep -E '^\[  PASSED  \]' "$SP/t_snap.txt" | tail -1)   (no golden refreshed)"
echo ""
echo "===== OI-170 Task 1 — MECHANICAL ENUMERATION (completeness basis) ====="
echo "Instrument-commit: $(git rev-parse --short HEAD)  (pre-commit working tree)"
echo ""
echo "--- SWEEP 1: every tonic-derived construction, the L4 file set + the notation bridges"
echo "    pattern: $SW"
echo "    scope  : $L4DIRS"
echo "    (tests excluded; comments included so a commented-out use cannot hide)"
sweep_l4 | wc -l
echo "    ^ total hits in the L4 scope (all files, incl. declarations/comments)"
echo ""
echo "--- SWEEP 1b: the SAME pattern, WHOLE composing module + whole notation module (THE SCOPE CHECK)"
sweep_all | wc -l
echo "    ^ total hits tree-wide. The difference from SWEEP 1 is the OUT-OF-L4-SCOPE remainder,"
echo "      enumerated by file here — the completeness check on the scope itself (DT-26)."
remainder_files | while read -r f; do echo "      $f: $(grep -cE "$SW" "$f") hits"; done
SCOPED=$(sweep_l4 | wc -l)
TREE=$(sweep_all | wc -l)
REM=$(remainder_files | while read -r f; do grep -cE "$SW" "$f"; done | awk '{s+=$1} END {print s+0}')
echo "      ---- ARITHMETIC CHECK: tree-wide($TREE) - scoped($SCOPED) = $((TREE-SCOPED)); remainder enumerated above = $REM"
if [ $((TREE-SCOPED)) -eq "$REM" ]; then
    echo "      ---- RECONCILES: every out-of-scope hit is accounted for by file."
else
    echo "      ---- MISMATCH — hits exist that neither the scope nor the remainder listing accounts for. THIS IS A STOP."
fi
echo ""
echo "--- SWEEP 1c: the out-of-scope hits, LISTED (each read and classified in the report §2/§3)"
echo "    (derived from the same exclusion as 1b — not a hand-kept file list, so a new"
echo "     out-of-scope file cannot appear in the count above yet be missing from this listing)"
remainder_files | while read -r f; do grep -nE "$SW" "$f" | sed "s|^|$f:|"; done
echo ""
echo "--- SWEEP 2: the DECIDING sites only — a tonic-derived value in an executable expression"
echo "    in the L4 region/gate/refinement path + the diatonicToKey producer/consumers"
for f in src/composing/analysis/chord/chordanalyzer.cpp src/composing/analysis/chord/postscoringgates.cpp \
         src/composing/analysis/chord/chordsymbolformatter.cpp src/composing/analysis/function/harmonicfunctionlayer.cpp \
         src/composing/analysis/region/sparsechordrefinement.cpp src/composing/analysis/region/regionanalyzer.cpp \
         src/composing/analysis/section/sectionanalyzer.cpp src/composing/analysis/section/sectioncadencedetection.cpp \
         src/composing/analysis/function/functionromannumeral.cpp src/composing/analysis/function/functionrelationallabel.cpp \
         src/notation/internal/notationcomposingbridge.cpp src/notation/internal/notationimplodebridge.cpp; do
    printf '  %-58s %3s hits\n' "$(basename $f)" "$(grep -cE "$SW" $f 2>/dev/null || echo 0)"
done
echo ""
echo "--- SWEEP 3: every diatonicToKey WRITE in the tree (the producer + every re-derivation)"
grep -rn "diatonicToKey" src/composing src/notation --include=*.cpp --include=*.h | grep -v "/tests/" \
    | grep -E "diatonicToKey[[:space:]]*=[^=]" | grep -v "keycollectionprobe"
echo ""
echo "--- SWEEP 4: every diatonicToKey READ of the PUBLISHED FIELD (consumers of the published fact)"
grep -rn "\.function\.diatonicToKey\|chord\.function\.diatonicToKey" src/composing src/notation \
    --include=*.cpp --include=*.h | grep -v "/tests/" | grep -vE "diatonicToKey[[:space:]]*=[^=]"
echo ""
echo "--- SWEEP 5: the parent-index table (chordanalyzer) and its duplicates"
grep -rn "0, 1, 2, 3, 4, 5, 6," src/composing --include=*.cpp | grep -v "/tests/"
echo ""
echo "===== ARMS 1-3: byte-identity, counters, flips ====="
for lp in baroque jazz default; do
    echo "########## PRESET: $lp ##########"
    echo "--- ARM 1: OFF path (both flags unset) vs committed tools/corpus/$lp"
    python tools/cc_oi168_probe_report.py byteid "$R/off/$lp" "tools/corpus/$lp" 2>&1
    echo "--- ARM 2: counters ON, variant OFF vs committed tools/corpus/$lp"
    python tools/cc_oi168_probe_report.py byteid "$R/cnt/$lp" "tools/corpus/$lp" 2>&1
    echo "--- ARM 2 counters"
    python tools/cc_oi168_probe_report.py counters "$R/cnt/$lp" --label "$lp counters-on variant-off" 2>&1
    echo "--- ARM 3: variant ON — flips vs the committed corpus"
    python tools/cc_oi168_probe_report.py flips "tools/corpus/$lp" "$R/var/$lp" 2>&1
    echo ""
done
echo "===== WHOLE-FILE byte-identity of the VARIANT corpus vs the committed corpus ====="
for lp in baroque jazz default; do
    echo "--- VARIANT corpus byte-identity vs committed tools/corpus/$lp"
    python tools/cc_oi168_probe_report.py byteid "$R/var/$lp" "tools/corpus/$lp" 2>&1
done
echo ""
echo "===== WHICH JSON KEYS CHANGE in the differing Jazz files (line-level diff) ====="
for s in $(python tools/cc_oi168_probe_report.py byteid "$R/var/jazz" tools/corpus/jazz 2>&1 \
           | grep "differs:" | awk '{print $2}'); do
    n=$(diff "tools/corpus/jazz/$s.ours.json" "$R/var/jazz/$s.ours.json" | grep -cE '^[<>]')
    k=$(diff "tools/corpus/jazz/$s.ours.json" "$R/var/jazz/$s.ours.json" | grep -oE '"[a-zA-Z]+":' | sort -u | tr '\n' ' ')
    printf '  %-10s changed lines: %2s   keys changed: %s\n' "$s" "$n" "$k"
done
echo ""
echo "===== THE HARD STOP on the VARIANT corpus (a8_rebaseline_measure + robust_stop_diff) ====="
cat "$SP/a8.log"
echo ""
cat "$SP/rsd.log"
echo ""
echo "===== pipeline-snapshot goldens: do they carry diatonicToKey / an Altered-family key? ====="
echo "grep -rl diatonicToKey src/notation/tests/pipeline_snapshot_tests/  -> $(grep -rl diatonicToKey src/notation/tests/pipeline_snapshot_tests/ 2>/dev/null | wc -l) files"
echo "grep -rl 'alt\"' src/notation/tests/pipeline_snapshot_tests/       -> $(grep -rl 'alt"' src/notation/tests/pipeline_snapshot_tests/ 2>/dev/null | wc -l) files"
} > "$OUT" 2>&1
echo "wrote $OUT"
